server:
  port: 9000

spring:
  application:
    name: btos

  datasource:
    platform: mysql
    url: jdbc:mysql://btos.cp3evafquu7f.ap-northeast-2.rds.amazonaws.com:3306/BTOS
    username: btos
    password: btos1234
    driver-class-name: com.mysql.cj.jdbc.Driver
