server:
#  port: 9000 # dev
  port: 9001 # prod

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: btos.cp3evafquu7f.ap-northeast-2.rds.amazonaws.com/BTOS
    username: btos
    password: btos1234
    driver-class-name: com.mysql.cj.jdbc.Driver
