spring:
  profiles:
    group:
      "local": "testDB, common"
      "dev": "testDB, common"
      "prod": "prodDB, prod"

---

spring:
  config:
    activate:
      on-profile: "testDB"
  datasource:
    platform: mysql
    url: ${DATASOURCE_URL_TESTDB}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9000

---

spring:
  config:
    activate:
      on-profile: "prodDB"
  datasource:
    platform: mysql
#    url:
#    username:
#    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

---

spring:
  config:
    activate:
      on-profile: "common"

server:
  port: 9000

---

spring:
  config:
    activate:
      on-profile: "prod"

server:
  port: 9001
