# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: pull main branch in EC2 dev
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: |
            cd /var/www/BTOS/dev/BTOS
            sudo chmod -R 777 /var/www/BTOS/dev/BTOS/.gradle/7.3.1/fileHashes/fileHashes.lock
            sudo chmod -R 777 /var/www/BTOS/dev/BTOS/.gradle/7.3.1/checksums/checksums.lock
            sudo chmod -R 777 /var/www/BTOS/dev/BTOS/.gradle/7.3.1/fileChanges/last-build.bin
            git pull origin main
            pkill -9 -ef "java -jar build/libs/BTOS-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev --DATASOURCE_URL_TESTDB=*** --DATASOURCE_USERNAME=*** --DATASOURCE_PASSWORD=***"
            ./gradlew clean build
            nohup java -jar build/libs/BTOS-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev --DATASOURCE_URL_TESTDB=*** --DATASOURCE_USERNAME=*** --DATASOURCE_PASSWORD=*** &
